export enum IAction {
  CREATE   = "create",
  QUERY    = "query",
  UPDATE   = "update",
  DELETE   = "delete",
  ROTATE   = "rotate",
  INVOKE   = "invoke",
  UPGRADE  = "upgrade",
  WILDCARD = "*",
}

export enum IResource {
  PROFILE      = "profile",
  ROLE         = "role",
  USERS        = "users",
  PAYMENTS     = "payments",
  INVENTORY    = "inventory",
  PRODUCT      = "product",
  ORDERS       = "orders",
  REVIEW       = "review",
  COLORS       = "colors",
  VIEW         = "view",
  CART         = "cart",
  AUDIT        = "audit",
  NOTIFICATION = "notification",
  STORE        = "store",
  ORGANIZATION = "organization",
  SUBSCRIPTION = "subscription",
  DOMAIN       = "domain",
  WILDCARD     = "*",
}