load_definitions = /etc/rabbitmq/definitions.json
log.console = true
log.console.level = info
log.file = false
heartbeat = 60
max_message_size = 10485760
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB
prometheus.tcp.port = 15692
management.tcp.port = 15672
 