export const MDASData = [
  {
    userType: "MDA",
    tin: "MDA-FVRVLI6IR",
    email: "essienedidiong1000@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    mdaRole: "ADMIN",
  },
  {
    userType: "MDA",
    tin: "MDA-w0HTgby2u",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    mdaRole: "SUB_DIRECTOR",
  },
  {
    userType: "MDA",
    tin: "MDA-elX7s8PBK",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    mdaRole: "COMPLIANCE",
  },
  {
    userType: "MDA",
    tin: "MDA-DC3-3axqt",
    email: "essienedidiong1000@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    mdaRole: "FINANCE_OFFICER",
  },
];

export const PAYEData = [
  {
    userType: "PAYE",
    tin: "PAY-JW73GGN",
    email: "essienedidiong1000@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    payeRole: "ADMIN",
  },
   {
    userType: "PAYE",
    tin: "PAY-TW43GGN",
    email: "essienedidiong1000@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    payeRole: "SUB_DIRECTOR1",
  },
  {
    userType: "PAYE",
    tin: "PAY-KGS21Q3",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    payeRole: "ADMIN",
  },
  {
    userType: "PAYE",
    tin: "PAY-PVkEVMC",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    payeRole: "SUB_DIRECTOR1",
  },
];

export const ASSESSMENTData = [
  {
    userType: "ASSESSMENT",
    tin: "ASS-JW73GGNN1",
    email: "essienedidiong1000@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    assessmentRole: "ADMIN",
  },
  {
    userType: "ASSESSMENT",
    tin: "ASS-KGS21Q3WK",
    email: "mykeetefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    assessmentRole: "ADMIN",
  },
  {
    userType: "ASSESSMENT",
    tin: "ASS-PVkEVMCYR",
    email: "mykeetefia@gmail.com",
    phone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    assessmentRole: "AUDITOR",
  },
];

export const AgentData = [
  {
    userType: "AGENT",
    tin: "AGT-JW73GGNN1",
    email: "essienedidiong1000@gmail.com",
    phone: "07065819848",
    secondaryPhone: "07065819848",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    agentRole: "ADMIN",
    licenseNumber: "32636dgdjk",
  },
  {
    userType: "AGENT",
    tin: "AGT-KGS21Q3WK",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    secondaryPhone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    agentRole: "ADMIN",
    licenseNumber: "32636dgdjk",
  },
  {
    userType: "AGENT",
    tin: "AGT-KGS24Q3WK",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    secondaryPhone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    agentRole: "SUPERVISOR",
    licenseNumber: "32636dgdjk",
  },
];
// SuperAdminData
export const SuperAdminData = [
  {
    userType: "SUPERADMIN",
    firstName: "Victor",
    lastName: "Essien",
    tin: "SUP-JW23GGNN1",
    email: "essienedidiong1000@gmail.com",
    phone: "07065819848",
    secondaryPhone: "07065819848",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
  {
    userType: "SUPERADMIN",
    tin: "SUP-K3S21Q3WK",
    firstName: "Myke",
    lastName: "Etefia",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    secondaryPhone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
];
// AdminAdminstrators

export const AdminAdminstrators = [
  {
    userType: "ADMIN",
    firstName: "Victor",
    lastName: "Essien",
    tin: "ADM-TEENKZQ",
    email: "essienedidiong1000@gmail.com",
    phone: "07065819848",
    secondaryPhone: "07065819848",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
  {
    userType: "ADMIN",
    tin: "ADM-JPUJ5WB",
    firstName: "Myke",
    lastName: "Etefia",
    email: "myketefia@gmail.com",
    phone: "+2348033917889",
    secondaryPhone: "+2348033917889",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
];


export const ChairmanAdminData = [
  {
    userType: "CHAIRMAN",
    tin: "CHR-J973GGN",
    firstName: "Victor",
    lastName: "Essien",
    email: "essienedidiong1000@gmail.com",
    phone: "07065819848",
    secondaryPhone: "07065819848",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
  {
    userType: "CHAIRMAN",
    tin: "CHR-K9S21Q3",
    firstName: "Myke",
    lastName: "Etefia",
    email: "myketefia@gmail.com",
    phone: "08187654321",
    secondaryPhone: "08187654321",
    authOptions: "APP",
    lga: "Uyo",
    state: "Akwa Ibom",
    revenueLines: [],
    jurisdiction: "Akwa Ibom",
    licenseNumber: "32636dgdjk",
  },
];
